version: "3.8"

services:
  db:
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    env_file:
      - ./db/.env
    volumes:
      - ./db/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh:ro
      - ./db/pg_hba.conf:/config/pg_hba.conf
      - db_data:/var/lib/postgresql/data:rw
    healthcheck:
      test: pg_isready -U postgres
      interval: 1s
      timeout: 1s
      retries: 30
    command: "postgres -c hba_file=/config/pg_hba.conf"

volumes:
  db_data:
    driver: local